export { default as Navbar } from './Navbar'
export { default as Cryptocurrencies } from './cryptocurrencies/Cryptocurrencies'
export { default as Exchange } from './Exchange'
export { default as HomePage } from './home/HomePage'
export { default as News } from './News'
export { default as CryptoDetails } from './cryptoDetails/CryptoDetails'